In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

print(sys.executable)  #

/home/nasim/Desktop/work/rag/sec-10k-rag/.venv/bin/python

In [3]:
from sec_10k_rag.step_05_embedding.load import load_chunks

In [4]:
from sec_10k_rag.step_05_embedding.config import ConfigType, get_config

In [5]:
from pprint import pprint

In [6]:
from sentence_transformers import SentenceTransformer

In [7]:
config = get_config(ConfigType.LOAD_CHUNKS)

In [8]:
pprint(config)

Config(command='run',
       root_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag'),
       input_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed'),
       processed_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/embedding'),
       log_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/logs'),
       temp_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/temp'),
       instructions=None)

In [9]:
input_data = load_chunks(config, "chunks.parquet")

In [10]:
display(input_data.head(10))

shape: (10, 10)
┌─────────────┬─────────────┬─────────────┬────────┬───┬──────┬──────────┬────────────┬────────────┐
│ chunk_index ┆ text        ┆ section_id  ┆ ticker ┆ … ┆ item ┆ title    ┆ report_dat ┆ source_url │
│ ---         ┆ ---         ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ e          ┆ ---        │
│ i64         ┆ str         ┆ str         ┆ str    ┆   ┆ str  ┆ str      ┆ ---        ┆ str        │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆ date       ┆            │
╞═════════════╪═════════════╪═════════════╪════════╪═══╪══════╪══════════╪════════════╪════════════╡
│ 0           ┆ Item 1      ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ Note About  ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ Forward-Loo ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ k…          ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 1           ┆ PART I      ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ ITEM 1.     ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ BUSINESS    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ GENERA…     ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 2           ┆ We develop  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ and support ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ a broad…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 3           ┆ We offer an ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ array of    ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ services,…  ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 4           ┆ We          ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ prioritize  ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ security    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ above a…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 5           ┆ •Build the  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ intelligent ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ cloud a…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 6           ┆ •Tackling   ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ security    ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ from all    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ an…         ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 7           ┆ •Providing  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ a unified   ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ intellige…  ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 8           ┆ OPERATING   ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ SEGMENTS    ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ We operate  ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ …           ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 9           ┆ Our         ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ reportable  ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ segments    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ are de…     ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
└─────────────┴─────────────┴─────────────┴────────┴───┴──────┴──────────┴────────────┴────────────┘

In [11]:
token_config = get_config(ConfigType.TOKENIZE)

In [12]:
pprint(token_config)

Config(command='run',
       root_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag'),
       input_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/embedding'),
       processed_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/embedding'),
       log_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/logs'),
       temp_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/temp'),
       instructions=EmbeddingInstructions(model_name='BAAI/bge-small-en-v1.5',
                                          batch_size=64))

In [13]:
model = SentenceTransformer(token_config.instructions.model_name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [14]:
from sec_10k_rag.step_05_embedding.tokenize import tokenize

In [15]:
tokenize(token_config, input_data)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (513 > 512). Running this sequence through the model will result in indexing errors

shape: (2_977, 4)
┌──────────────────┬─────────────┬──────────┬───────────┐
│ section_id       ┆ chunk_index ┆ n_tokens ┆ truncated │
│ ---              ┆ ---         ┆ ---      ┆ ---       │
│ str              ┆ i64         ┆ u32      ┆ bool      │
╞══════════════════╪═════════════╪══════════╪═══════════╡
│ MSFT-2026-item1  ┆ 0           ┆ 397      ┆ false     │
│ MSFT-2026-item1  ┆ 1           ┆ 55       ┆ false     │
│ MSFT-2026-item1  ┆ 2           ┆ 181      ┆ false     │
│ MSFT-2026-item1  ┆ 3           ┆ 257      ┆ false     │
│ MSFT-2026-item1  ┆ 4           ┆ 86       ┆ false     │
│ …                ┆ …           ┆ …        ┆ …         │
│ TSLA-2023-item15 ┆ 32          ┆ 252      ┆ false     │
│ TSLA-2023-item15 ┆ 33          ┆ 326      ┆ false     │
│ TSLA-2023-item15 ┆ 34          ┆ 80       ┆ false     │
│ TSLA-2023-item16 ┆ 0           ┆ 246      ┆ false     │
│ TSLA-2023-item16 ┆ 1           ┆ 82       ┆ false     │
└──────────────────┴─────────────┴──────────┴───────────┘

In [16]:
from sec_10k_rag.step_05_embedding.vectorize import vectorize

In [17]:
vectorized_config = get_config(ConfigType.VECTORIZE)

In [18]:
embedded_df = vectorize(vectorized_config, input_data)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/47 [00:00<?, ?it/s]

In [20]:
print(embedded_df.columns)

['chunk_index', 'text', 'section_id', 'ticker', 'cik', 'fiscal_year', 'item', 'title', 'report_date', 'source_url', 'embedding']

In [21]:
display(embedded_df["embedding"])

shape: (2_977,)
Series: 'embedding' [array[f32, 384]]
[
	[0.012052, -0.014693, … -0.000472]
	[0.007018, 0.002022, … 0.021544]
	[-0.032677, -0.012149, … 0.009559]
	[-0.018031, -0.066286, … 0.044042]
	[-0.015454, -0.050848, … -0.008764]
	…
	[-0.064206, 0.002793, … 0.051612]
	[-0.012745, -0.057691, … 0.062489]
	[0.000501, -0.054383, … 0.021327]
	[-0.003975, 0.018073, … 0.036923]
	[0.028651, 0.047558, … 0.032858]
]